# Generated by Django 5.0.1 on 2024-02-11 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
