# Generated by Django 5.0.1 on 2024-02-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
