# Generated by Django 5.0.1 on 2024-02-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0010_remove_profile_verified_profile_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='address_business',
        ),
        migrations.AddField(
            model_name='profile',
            name='address_home',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_office',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
