# Generated by Django 5.0.1 on 2024-03-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0014_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address_business',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address_home',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address_office',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
