# Generated by Django 5.0.1 on 2024-03-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0016_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='title',
            field=models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('business', 'Business')], max_length=10, null=True),
        ),
    ]
