# Generated by Django 5.0.1 on 2024-03-24 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_order_address_address'),
        ('userauths', '0017_alter_address_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
