# Generated by Django 5.0.1 on 2024-03-24 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0018_delete_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('business', 'Business')], max_length=10, null=True)),
                ('street_address', models.TextField()),
                ('city_district_town', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userauths_addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
