# Generated by Django 5.0.1 on 2024-04-08 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0021_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='title',
        ),
    ]
