# Generated by Django 5.0.1 on 2024-04-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0024_remove_address_first_name_remove_address_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='first_name1',
        ),
        migrations.RemoveField(
            model_name='address',
            name='last_name1',
        ),
        migrations.AlterField(
            model_name='address',
            name='title',
            field=models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('business', 'Business')], default='Home', max_length=10, null=True),
        ),
    ]
