# Generated by Django 5.0.1 on 2024-01-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_products_tags_products_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(default='1.99', max_length=20),
        ),
    ]
