# Generated by Django 5.0.1 on 2024-01-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='old_price',
            field=models.CharField(default='1.99', max_length=20),
        ),
    ]
