# Generated by Django 5.0.1 on 2024-02-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_productreview_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='link_video',
            field=models.CharField(default='www.youtube.com', max_length=100),
        ),
    ]
