# Generated by Django 5.0.1 on 2024-02-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_orders_items_json_remove_orders_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='mobile_number',
            field=models.IntegerField(default=24343, max_length=9999999999),
        ),
    ]
