# Generated by Django 5.0.1 on 2024-02-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_orders_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='TVs', max_length=100, unique=True),
        ),
    ]
