# Generated by Django 5.0.1 on 2024-02-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Televisions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='laptops',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='smart_phone',
            field=models.BooleanField(default=False),
        ),
    ]
