# Generated by Django 5.0.1 on 2024-02-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_products_televisions_products_laptops_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Televisions',
        ),
        migrations.RemoveField(
            model_name='products',
            name='laptops',
        ),
        migrations.RemoveField(
            model_name='products',
            name='smart_phone',
        ),
    ]
