# Generated by Django 5.0.1 on 2024-02-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_products_mobile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='mobile_phone',
            field=models.BooleanField(default=False),
        ),
    ]
