# Generated by Django 5.0.1 on 2024-03-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_products_mobile_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
