# Generated by Django 5.0.1 on 2024-03-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_order_orderitem_delete_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='sub_total',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_paid',
            field=models.CharField(max_length=200),
        ),
    ]
