# Generated by Django 5.0.1 on 2024-03-21 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_order_id_order_order_time_and_more'),
        ('userauths', '0016_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userauths.address'),
        ),
    ]
