# Generated by Django 5.0.1 on 2024-03-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_products_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitems',
            name='order',
        ),
        migrations.DeleteModel(
            name='CartOrder',
        ),
        migrations.DeleteModel(
            name='CartOrderItems',
        ),
    ]
