# Generated by Django 5.0.1 on 2024-03-24 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_cartorderitems_order_delete_cartorder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200)),
                ('p_price', models.CharField(max_length=200)),
                ('p_qty', models.IntegerField()),
                ('p_total', models.CharField(max_length=200)),
                ('total_amount', models.CharField(max_length=200)),
                ('discount', models.CharField(max_length=200)),
                ('total_paid', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
