# Generated by Django 5.0.1 on 2024-03-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_location',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
