# Generated by Django 5.0.1 on 2024-03-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_order_address_delete_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('received', 'Order Received'), ('processed', 'Order Processed'), ('shipped', 'Order Shipped'), ('delivered', 'Order Delivered')], default='received', max_length=20),
        ),
    ]
