# Generated by Django 5.0.1 on 2024-03-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(default='TV', max_length=100, unique=True),
        ),
    ]
