# Generated by Django 5.0.1 on 2024-03-27 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='order',
        ),
    ]
