# Generated by Django 5.0.1 on 2024-03-27 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_sale_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='order',
            field=models.ForeignKey(default=90, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='core.order'),
        ),
    ]
