# Generated by Django 5.0.1 on 2024-04-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_sale_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('received', 'Order Received'), ('processed', 'Order Processed'), ('shipped', 'Order Shipped'), ('delivered', 'Order Delivered')], default='Order Received', max_length=20),
        ),
    ]
