# Generated by Django 5.0.1 on 2024-04-08 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='core.order'),
        ),
    ]
