# Generated by Django 5.0.1 on 2024-04-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_sale_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selected_address_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
