# Generated by Django 5.0.1 on 2024-04-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_order_selected_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(default='Apple', max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
